# License policy and report configuration for cargo-about 0.9.1.
accepted = [
    "GPL-3.0-or-later",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "Zlib",
    "0BSD",
    "CC0-1.0",
    "MIT-0",
    "Unlicense",
    "MPL-2.0",
]

ignore-dev-dependencies = true

workarounds = [
    "ring",
    "rustls",
    "rustix",
]
