plugins {
    id "com.android.application"
}

android {
    namespace "com.example.logfilterproblemdemo"
    compileSdk 31

    defaultConfig {
        applicationId "com.example.logfilterproblemdemo"
        minSdk 23
        targetSdk 31
        versionCode 2
        versionName "1.1"

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
